### ISSUE TITLE
Include example for `kafka_mtls_principal_mapping_rules`

### ISSUE THREAD

**Issue by micheleRP** [redpanda-data/documentation#1625]
### Describe the Issue

Include example for `kafka_mtls_principal_mapping_rules`.

SME = Camilo Aguilar, Ben Pope
- See https://redpandadata.slack.com/archives/C01LK3UK2K1/p1684902241053559 
- See https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=89071740, which is the KIP the feature implements.

There's an example on the PR https://github.com/redpanda-data/redpanda/pull/4501
[#4501 kafka: mTLS principal mapping](https://github.com/redpanda-data/redpanda/pull/4501)
Fixes [#3939](https://github.com/redpanda-data/redpanda/issues/3939)

Enable the feature:

`curl -X PUT http://localhost:9644/v1/features/mtls_authentication -d '{"state":"active"}'`

Configuration looks like:

```
redpanda:
  kafka_api_tls:
    - cert_file: mtls_server.crt
      enabled: true
      key_file: mtls_server.key
      name: kafka-external
      require_client_auth: true
      principal_mapping_rules: "RULE:.*CN=([^,]+).*/$1/, DEFAULT"
      truststore_file: mtls_ca.crt
```

### Updates to existing documentation

https://docs.redpanda.com/docs/manage/security/authentication/#configure-mtls-with-authentication
