### ISSUE TITLE
k8s: enhance external connectivity with preferred addresses and load-balancer guide

### ISSUE THREAD

**Issue by dimitriscruz** [redpanda-data/documentation#254]
### Who is this for and what problem do they have today?

Two new features:
1. The operator selects an externalIP as the (Kafka) advertised IP. Users want to select other types of advertised addresses such as InternalIP. This feature was merged recently.
2.  In "real" deployments, users often want a load-balancer for bootstrapping. This feature was merged recently.

### What would you like fixed in or added to the documentation?

Add explanation/example of new features in external connectivity guide.

### Is this a new feature or a gap in the documentation?

New features, related to each other, added here:

- https://github.com/redpanda-data/redpanda/pull/3794
- https://github.com/redpanda-data/redpanda/pull/3896

#### If new feature, what's the expected release number and date? 

v22

### Link to existing product documentation page and/or community slack conversation, if applicable

- https://github.com/redpanda-data/redpanda/pull/3794
- https://github.com/redpanda-data/redpanda/pull/3896
- Slack: p-k8s-connectivity

Example of using both features
```
    kafkaApi:
      - port: 9092
      - tls:
          enabled: false
          requireClientAuth: false
        external:
          enabled: true
          preferredAddressType: InternalIP
          bootstrapLoadBalancer:
            port: 9092
            annotations:
              networking.gke.io/load-balancer-type: "Internal"
```
