### ISSUE TITLE
Improve Docker quickstart for a multi-node cluster

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/documentation#619]
### Describe the Issue

Our existing documentation around creating a multi-node cluster with docker could be shorter if we use Docker compose. An additional benefit to this approach would be that the mounted volumes would be in the current working directory rather than left up to Docker to decide (which likely means `/var/lib/docker/volumes/`, accessible only by root). Another benefit is the instructions below fix the container-based `rpk` command (the previous has a couple of issues).

The audience is the same as before: new users of Redpanda.

### Updates to existing documentation

https://docs.redpanda.com/docs/quickstart/quick-start-docker/#set-up-a-3-node-cluster

The existing section could be replace with the following:

===

The following steps show how to configure a local 3-node Redpanda cluster with docker compose.

#### Create the volume directories

Setup the local `volumes` directory (owned by the redpanda userID). Each container will mount their own sub-directory here:
```shell
mkdir -p volumes/{redpanda0,redpanda1,redpanda2}
sudo chown -R 101:101 volumes
```
#### Start Redpanda nodes

Save this content as `docker-compose.yml`:
```
version: "3.9"

services:
  redpanda0:
    container_name: redpanda0
    image: docker.vectorized.io/vectorized/redpanda
    command:
    - redpanda start
    - --smp 1
    - --memory 1G
    - --reserve-memory 0M
    - --overprovisioned
    - --node-id 0
    - --check=false
    - --set redpanda.auto_create_topics_enabled=false
    - --kafka-addr INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr INSIDE://redpanda0:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr INSIDE://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
    - --advertise-pandaproxy-addr INSIDE://redpanda0:28082,OUTSIDE://localhost:8082
    - --rpc-addr 0.0.0.0:33145
    - --advertise-rpc-addr redpanda0:33145
    - --kernel-page-cache 1
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 9644:9644
    volumes:
    - ./volumes/redpanda0:/var/lib/redpanda/data

  redpanda1:
    container_name: redpanda1
    image: docker.vectorized.io/vectorized/redpanda
    command:
    - redpanda start
    - --smp 1
    - --memory 1G
    - --reserve-memory 0M
    - --overprovisioned
    - --node-id 1
    - --seeds redpanda0:33145,redpanda2:33145
    - --check=false
    - --set redpanda.auto_create_topics_enabled=false
    - --kafka-addr INSIDE://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
    - --advertise-kafka-addr INSIDE://redpanda1:29093,OUTSIDE://localhost:9093
    - --pandaproxy-addr INSIDE://0.0.0.0:28083,OUTSIDE://0.0.0.0:8083
    - --advertise-pandaproxy-addr INSIDE://redpanda1:28083,OUTSIDE://localhost:8083
    - --rpc-addr 0.0.0.0:33145
    - --advertise-rpc-addr redpanda1:33145
    - --kernel-page-cache 1
    ports:
    - 8083:8083
    - 9093:9093
    - 9645:9644
    volumes:
    - ./volumes/redpanda1:/var/lib/redpanda/data

  redpanda2:
    container_name: redpanda2
    image: docker.vectorized.io/vectorized/redpanda
    command:
    - redpanda start
    - --smp 1
    - --memory 1G
    - --reserve-memory 0M
    - --overprovisioned
    - --node-id 2
    - --seeds redpanda0:33145,redpanda1:33145
    - --check=false
    - --set redpanda.auto_create_topics_enabled=false
    - --kafka-addr INSIDE://0.0.0.0:29094,OUTSIDE://0.0.0.0:9094
    - --advertise-kafka-addr INSIDE://redpanda2:29094,OUTSIDE://localhost:9094
    - --pandaproxy-addr INSIDE://0.0.0.0:28084,OUTSIDE://0.0.0.0:8084
    - --advertise-pandaproxy-addr INSIDE://redpanda2:28084,OUTSIDE://localhost:8084
    - --rpc-addr 0.0.0.0:33145
    - --advertise-rpc-addr redpanda2:33145
    - --kernel-page-cache 1
    ports:
    - 8084:8084
    - 9094:9094
    - 9646:9644
    volumes:
    - ./volumes/redpanda2:/var/lib/redpanda/data
```

Then start the nodes for the Redpanda cluster:
```shell
docker compose -p redpanda up
```

#### Cluster interaction with rpk

Now you can use `rpk` to interact with the cluster. This can be done three different ways: 1) from a local install, 2) from within the node, or 3) from an additional container.

1) Locally-installed `rpk`:
```shell
rpk cluster info
```

2) Node-based 'rpk':
```shell
docker exec -it redpanda1 rpk cluster info
```

3) Container-based `rpk`:
```shell
docker run --net redpanda_default docker.redpanda.com/vectorized/redpanda cluster info --brokers redpanda0:29092
```

The output of the command above (in any of the three examples) is something like the following:
```
CLUSTER
=======
redpanda.d4e583b7-bcb2-4316-9627-4ccf4880b67a

BROKERS
=======
ID    HOST       PORT
0*    redpanda0  29092
1     redpanda1  29093
2     redpanda2  29094
```

===
